create table customers(customer_id int primary key,name varchar(50),city varchar(50));
create table orderss(order_id int primary key,customer_id int,order_date date,amount int,foreign key (customer_id)references customers(customer_id));
insert into customers(customer_id,name,city) values (1,'jagruti','valsad'),(2,'riya','dharmpur'),(3,'kinjal','vapi'),(4,'kunju','dhaman'),(5,'piya','kajali'),(6,'lila','udhna'),(7,'hansha','kheda'),(8,'trupti','surat'),(9,'priya','sachin');
insert into orderss(order_id,customer_id,order_date,amount)values (101,1,'2026-02-10',60000),(102,2,'2026-02-11',15000),(103,3,'2026-02-12',1000),(104,4,'2026-02-20',80000),(105,5,'2026-02-13',5222),(106,6,'2026-02-18',3000),(107,7,'2026-02-06',1300),(108,8,'2026-05-15',900000),(109,9,'2026-03-10',400);
select * from customers;
select * from orderss;
select c.customer_id ,c.name ,o.order_id from customers c join orderss o on c.customer_id = o.customer_id;
select c.customer_id ,c.name ,count (o.order_id) as total_orderss from customers c join orderss o on c.customer_id = o.customer_id group by c.customer_id,c.name;
select c.customer_id ,c.name,count (o.order_id) as total_orderss from customers c left join orderss o on c.customer_id = o.customer_id group by c.customer_id ,c.name;
create table  products (product_id int primary key, product_name varchar(50),price int);
create table order_iteams(order_id int ,product_id int,quantity int ,foreign key (order_id )references orderss(order_id),foreign key (product_id) references products(product_id));
insert into products values (1,'mobile',1500),(2,'headphones',30000),(3,'laptop',500000),(4,'cpu',80000),(5,'pc',900),(6,'monotor',60000),(7,'mini phone',90000),(8,'tv',80000),(9,'reciver',700);
insert into order_iteams values (101,1,1),(102,3,2),(103,2,1),(104,4,1),(105,5,2),(106,6,2),(107,2,4),(108,8,1),(109,9,1);
select c.customer_id ,c.name, count (o.order_id )as total_orderss  from customers c left join orderss o on c.customer_id = o.customer_id group by c.customer_id , c.name;
select c.customer_id ,c.name from customers c left join orderss o ON c.customer_id = o.customer_id where o.order_id is null;
select p.product_name, sum(oi.quantity) as total_sold from products p join order_iteams oi on p.product_id = oi.product_id group by p.product_name order by total_sold desc limit 1;
select extract (year from order_date) as year,extract (month from order_date) as month, sum (amount) as total_sales from orders group by year ,month order by year,month;
select c.customer_id ,c.name,sum(o.amount) as total_purchase from customers c join orderss o on c.customer_id = o.customer_id group by c.customer_i 3,aving sum(o.amount) > 50000;
select c.city ,sum(o.amount) as total_revenue from customers c join orderss o on c.customer_id = o.customer_id group by c.city order by total_revenue desc limit 3;
